spring:
  application:
    name: "api-gateway"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 2s
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "api-gateway"
    description: "Eazy bank api-gateway application"
    version: "1.0.0"

logging:
  level:
    com:
      learnmicroservice: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
#        circuit breaker se su dung 10 request gan nhat de danh gia ty le loi
        sliding-window-size: 10
#        so luong yeu cau duoc phep di qua circuit breaker khi no o trang thai half-open
        permitted-number-of-calls-in-half-open-state: 2
#        ty le loi duoc phep toi da(theo phan tram) truoc khi Circuit Breaker chuyen sang trang thai Open
        failure-rate-threshold: 50
#        thoi gian cho(tinh bang mili giay) ma Circuit Breaker se o trang thai Open truoc khi chuyen sang Half-Open
        wait-duration-in-open-state: 10000