spring:
  application:
    name: "api-gateway"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "api-gateway"
    description: "Eazy bank api-gateway application"
    version: "1.0.0"

logging:
  level:
    com:
      learnmicroservice: DEBUG