services:
  accountdb:
    container_name: accountdb
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: accountdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  loandb:
    container_name: loandb
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: loandb
    extends:
      file: common-config.yml
      service: microservice-db-config

  carddb:
    container_name: carddb
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: carddb
    extends:
      file: common-config.yml
      service: microservice-db-config
  config-server:
    image: "hachnv/config-server:s7"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  account-service:
    image: "hachnv/account-service:s7"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
      accountdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "account-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountdb:3306/accountdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loan-service:
    image: "hachnv/loan-service:s7"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loan-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loandb:3306/loandb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  card-service:
    image: "hachnv/card-service:s7"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_healthy
      carddb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "card-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://carddb:3306/carddb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  eazybank:
    driver: "bridge"