services:
  account-service:
    image: "hachnv/account-service:s4"
#    this name will be used when run a container instead of random name
    container_name: "account-ms"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
  loan-service:
    image: "hachnv/loan-service:s4"
    #    this name will be used when run a container instead of random name
    container_name: "loan-ms"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
  card-service:
    image: "hachnv/card-service:s4"
    #    this name will be used when run a container instead of random name
    container_name: "card-ms"
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
networks:
  eazybank:
    driver: "bridge"