build:
  version: "1.0"
account:
  message: "Welcome to Eazybank account related to Prod API."
  contactDetails:
    name: "John Doe - Product Own"
    email: "JohnDoe@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1234