server:
  port: 8080

spring:
  application:
    name: card-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:carddb
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
